### ISSUE TITLE
Ruy is not installed and started correctly

### ISSUE THREAD

**Issue by cstritzke** [fp7-netide/IDE#7]
The ryu installation script and the start command is currently not working. I sorted out the following reasons:
1. The folder ryu-shim/netide does not exist anymore -> installation fails
2. The ryu backend script name has been changed from "backend.py" to "ryu-backend.py" -> startup fails

**Comment by farhaven** [comment]
I pushed a fix for those a few minutes ago. There's one remaining problem now, which is that the `netip` library that does all the wrapping of flow messages can't be found because it's not installed properly right now.

My suggestion would be to turn that library into a Python module that can be installed with Pip, but I think that's better discussed in the Engine issue tracker.

**Comment by andres-beato** [comment]
I think the problem here is that the script was prepared to catch the ryu
shim and the ryu backend from the development branch, where currently the
version of Ryu shim and backend are prepared to run with the new core, so
we have to catch the old version of ryu shim and backend from the
"pyretic_intermediate_protocol" branch.

2015-10-07 15:58 GMT+02:00 Gregor Best notifications@github.com:

**Comment by ElisaRojas** [comment]
Hi, I've been talking with @andres-beato about this. To summarize a bit more: Currently there is a pyretic_interm... feature branch in the Engine, with all the old stuff. Our scripts do not work anymore because the Engine master/development branches have mixed functionalities (some with the new core and some with the old Pyretic API).

Therefore, the solution is:
- On one hand: we create a pyretic_interm... feature branch with the current status of the IDE, update the scripts to work with that branch of the Engine. No merging after this.
- On the other hand: start developing the new scripts as another feature branch that will be later merged in the 'master' branch. This will only include the Ryu backend and shim, and the core, which are the only components available right now. The NetIP lib should be installed as well.

So guys, no rush, Andrés is working on this. But, before of all of this, Ryu+Core should work! and this is what he is trying to do right now with Sergio.

**Comment by doriguzzi** [comment]
Hi Elisa,

I totally agree with you.

--rob

**Comment by cstritzke** [comment]
Thanks for looking into this. I'll try to build a new vm with the branch and update the Eclipse-MP version when it works.

**Comment by cstritzke** [comment]
Just tried the pyretic_interm... branch and it works. Thanks!
